Resources:
  BidsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "bidId"
          "AttributeType": "S"
        - "AttributeName": "buyerId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "buyerId"
          "KeyType": "HASH"
        - AttributeName: "bidId"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Bids"
