Resources:
  VehicleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
        - "AttributeName": "make"
          "AttributeType": "S"
        - "AttributeName": "model"
          "AttributeType": "S"
        - "AttributeName": "model"
          "AttributeType": "S"
        - "AttributeName": "year"
          "AttributeType": "S"
        - "AttributeName": "sellerId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Vehicle"
